site_name: Minicli 2
theme:
  name: material
  palette:
    primary: purple
    accent: purple
  icon:
    logo: material/console
    repo: fontawesome/brands/git-alt
  features:
    - navigation.sections
    - toc.integrate
repo_name: minicli/minicli
repo_url: https://github.com/minicli/minicli
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true